/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/wheel-new.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/wheel-new.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="face1" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle002"
            geometry={nodes.Circle002.geometry}
            material={materials['face1 mat 2']}
          />
          <mesh
            name="Circle002_1"
            geometry={nodes.Circle002_1.geometry}
            material={materials['face1 mat 1']}
          />
          <mesh
            name="Circle002_2"
            geometry={nodes.Circle002_2.geometry}
            material={materials['face1 mat 3']}
          />
        </group>
        <group name="face11" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle028"
            geometry={nodes.Circle028.geometry}
            material={materials['face1.1 mat 2']}
          />
          <mesh
            name="Circle028_1"
            geometry={nodes.Circle028_1.geometry}
            material={materials['face1.1 mat 1']}
          />
          <mesh
            name="Circle028_2"
            geometry={nodes.Circle028_2.geometry}
            material={materials['face1.1 mat 3']}
          />
        </group>
        <group name="face12" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle035"
            geometry={nodes.Circle035.geometry}
            material={materials['face1.2 mat 2']}
          />
          <mesh
            name="Circle035_1"
            geometry={nodes.Circle035_1.geometry}
            material={materials['face1.2 mat 1']}
          />
          <mesh
            name="Circle035_2"
            geometry={nodes.Circle035_2.geometry}
            material={materials['face1.2 mat 3']}
          />
        </group>
        <group name="face13" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle031"
            geometry={nodes.Circle031.geometry}
            material={materials['face1.3 mat 2']}
          />
          <mesh
            name="Circle031_1"
            geometry={nodes.Circle031_1.geometry}
            material={materials['face1.3 mat 1']}
          />
          <mesh
            name="Circle031_2"
            geometry={nodes.Circle031_2.geometry}
            material={materials['face1.3 mat 3']}
          />
        </group>
        <group name="face2" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle007"
            geometry={nodes.Circle007.geometry}
            material={materials['face2 mat 2']}
          />
          <mesh
            name="Circle007_1"
            geometry={nodes.Circle007_1.geometry}
            material={materials['face2 mat 1']}
          />
          <mesh
            name="Circle007_2"
            geometry={nodes.Circle007_2.geometry}
            material={materials['face2 mat 3']}
          />
          <mesh
            name="Circle007_3"
            geometry={nodes.Circle007_3.geometry}
            material={materials['face2 mat 4']}
          />
        </group>
        <group name="face21" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle030"
            geometry={nodes.Circle030.geometry}
            material={materials['face2.1 mat 2']}
          />
          <mesh
            name="Circle030_1"
            geometry={nodes.Circle030_1.geometry}
            material={materials['face2.1 mat 1']}
          />
          <mesh
            name="Circle030_2"
            geometry={nodes.Circle030_2.geometry}
            material={materials['face2.1 mat 3']}
          />
          <mesh
            name="Circle030_3"
            geometry={nodes.Circle030_3.geometry}
            material={materials['face2.1 mat 4']}
          />
        </group>
        <group name="face3" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle006"
            geometry={nodes.Circle006.geometry}
            material={materials['face3 mat 2']}
          />
          <mesh
            name="Circle006_1"
            geometry={nodes.Circle006_1.geometry}
            material={materials['face3 mat 1']}
          />
          <mesh
            name="Circle006_2"
            geometry={nodes.Circle006_2.geometry}
            material={materials['face3 mat 3']}
          />
          <mesh
            name="Circle006_3"
            geometry={nodes.Circle006_3.geometry}
            material={materials['face3 mat 4']}
          />
        </group>
        <group name="face31" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle022"
            geometry={nodes.Circle022.geometry}
            material={materials['face3.1 mat 2']}
          />
          <mesh
            name="Circle022_1"
            geometry={nodes.Circle022_1.geometry}
            material={materials['face3.1 mat 1']}
          />
          <mesh
            name="Circle022_2"
            geometry={nodes.Circle022_2.geometry}
            material={materials['face3.1 mat 3']}
          />
          <mesh
            name="Circle022_3"
            geometry={nodes.Circle022_3.geometry}
            material={materials['face3.1 mat 4']}
          />
        </group>
        <group name="face32" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle027"
            geometry={nodes.Circle027.geometry}
            material={materials['face3.2 mat 2']}
          />
          <mesh
            name="Circle027_1"
            geometry={nodes.Circle027_1.geometry}
            material={materials['face3.2 mat 1']}
          />
          <mesh
            name="Circle027_2"
            geometry={nodes.Circle027_2.geometry}
            material={materials['face3.2 mat 3']}
          />
          <mesh
            name="Circle027_3"
            geometry={nodes.Circle027_3.geometry}
            material={materials['face3.2 mat 4']}
          />
        </group>
        <group name="face4" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle032"
            geometry={nodes.Circle032.geometry}
            material={materials['face4 mat 2']}
          />
          <mesh
            name="Circle032_1"
            geometry={nodes.Circle032_1.geometry}
            material={materials['face4 mat 1']}
          />
          <mesh
            name="Circle032_2"
            geometry={nodes.Circle032_2.geometry}
            material={materials['face4 mat 3']}
          />
          <mesh
            name="Circle032_3"
            geometry={nodes.Circle032_3.geometry}
            material={materials['face4 mat 4']}
          />
        </group>
        <group name="face5" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle024"
            geometry={nodes.Circle024.geometry}
            material={materials['face5 mat 2']}
          />
          <mesh
            name="Circle024_1"
            geometry={nodes.Circle024_1.geometry}
            material={materials['face5 mat 1']}
          />
          <mesh
            name="Circle024_2"
            geometry={nodes.Circle024_2.geometry}
            material={materials['face5 mat 3']}
          />
        </group>
        <group name="face6" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle025"
            geometry={nodes.Circle025.geometry}
            material={materials['face6 mat 2']}
          />
          <mesh
            name="Circle025_1"
            geometry={nodes.Circle025_1.geometry}
            material={materials['face6 mat 1']}
          />
          <mesh
            name="Circle025_2"
            geometry={nodes.Circle025_2.geometry}
            material={materials['face6 mat 3']}
          />
          <mesh
            name="Circle025_3"
            geometry={nodes.Circle025_3.geometry}
            material={materials['face6 mat 4']}
          />
        </group>
        <group name="face7" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle008"
            geometry={nodes.Circle008.geometry}
            material={materials['face7 mat 2']}
          />
          <mesh
            name="Circle008_1"
            geometry={nodes.Circle008_1.geometry}
            material={materials['face7 mat 1']}
          />
          <mesh
            name="Circle008_2"
            geometry={nodes.Circle008_2.geometry}
            material={materials['face7 mat 3']}
          />
          <mesh
            name="Circle008_3"
            geometry={nodes.Circle008_3.geometry}
            material={materials['face7 mat 4']}
          />
        </group>
        <group name="face8" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle023"
            geometry={nodes.Circle023.geometry}
            material={materials['face8 mat 2']}
          />
          <mesh
            name="Circle023_1"
            geometry={nodes.Circle023_1.geometry}
            material={materials['face8 mat 1']}
          />
          <mesh
            name="Circle023_2"
            geometry={nodes.Circle023_2.geometry}
            material={materials['face8 mat 3']}
          />
          <mesh
            name="Circle023_3"
            geometry={nodes.Circle023_3.geometry}
            material={materials['face8 mat 4']}
          />
        </group>
        <group name="face9" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle026"
            geometry={nodes.Circle026.geometry}
            material={materials['face9 mat 2']}
          />
          <mesh
            name="Circle026_1"
            geometry={nodes.Circle026_1.geometry}
            material={materials['face9 mat 1']}
          />
          <mesh
            name="Circle026_2"
            geometry={nodes.Circle026_2.geometry}
            material={materials['face9 mat 3']}
          />
        </group>
        <group name="face10" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle029"
            geometry={nodes.Circle029.geometry}
            material={materials['face10 mat 2']}
          />
          <mesh
            name="Circle029_1"
            geometry={nodes.Circle029_1.geometry}
            material={materials['face10 mat 1']}
          />
          <mesh
            name="Circle029_2"
            geometry={nodes.Circle029_2.geometry}
            material={materials['face10 mat 3']}
          />
          <mesh
            name="Circle029_3"
            geometry={nodes.Circle029_3.geometry}
            material={materials['face10 mat 4']}
          />
        </group>
        <group name="Circle016" rotation={[Math.PI / 2, -0.471, 0]}>
          <mesh
            name="Circle003"
            geometry={nodes.Circle003.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Circle003_1"
            geometry={nodes.Circle003_1.geometry}
            material={materials['face1 mat 2']}
          />
          <mesh
            name="Circle003_2"
            geometry={nodes.Circle003_2.geometry}
            material={materials['face1 mat 1']}
          />
          <mesh
            name="Circle003_3"
            geometry={nodes.Circle003_3.geometry}
            material={materials['Material.015']}
          />
          <mesh
            name="Circle003_4"
            geometry={nodes.Circle003_4.geometry}
            material={materials['face1 mat 3']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wheel-new.glb')
